/*
 * digits.c
 *
 *  Created on: 12 gru 2015
 *      Author: Jonasz
 */

#include "digits.h"
#include "display.h"

void setZero() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_D;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_E;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_F;
	PORT(SEGMENTS_PORT) |= SEGMENT_G;

}

void setOne() {

	PORT(SEGMENTS_PORT) |= SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) |= SEGMENT_D;
	PORT(SEGMENTS_PORT) |= SEGMENT_E;
	PORT(SEGMENTS_PORT) |= SEGMENT_F;
	PORT(SEGMENTS_PORT) |= SEGMENT_G;

}

void setTwo() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) |= SEGMENT_C;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_D;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_E;
	PORT(SEGMENTS_PORT) |= SEGMENT_F;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_G;

}

void setThree() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_D;
	PORT(SEGMENTS_PORT) |= SEGMENT_E;
	PORT(SEGMENTS_PORT) |= SEGMENT_F;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_G;

}

void setFour() {

	PORT(SEGMENTS_PORT) |= SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) |= SEGMENT_D;
	PORT(SEGMENTS_PORT) |= SEGMENT_E;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_F;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_G;

}

void setFive() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) |= SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_D;
	PORT(SEGMENTS_PORT) |= SEGMENT_E;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_F;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_G;

}

void setSix() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) |= SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_D;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_E;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_F;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_G;

}

void setSeven() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) |= SEGMENT_D;
	PORT(SEGMENTS_PORT) |= SEGMENT_E;
	PORT(SEGMENTS_PORT) |= SEGMENT_F;
	PORT(SEGMENTS_PORT) |= SEGMENT_G;

}

void setEight() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_D;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_E;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_F;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_G;

}

void setNine() {

	PORT(SEGMENTS_PORT) &= ~SEGMENT_A;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_B;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_C;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_D;
	PORT(SEGMENTS_PORT) |= SEGMENT_E;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_F;
	PORT(SEGMENTS_PORT) &= ~SEGMENT_G;

}
